name: Fuel Indexer Release (nightly) 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prepare release
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      upload_url_plugin: ${{ steps.create-release-plugin.outputs.upload_url }}
      today: ${{ steps.set-date.outputs.today }}
      tag: ${{ steps.set-tag.outputs.tag }}
      name: ${{ steps.set-name.outputs.name }}
      plugin_name: ${{ steps.set-name.outputs.plugin_name }}
      commit_hash: ${{ steps.set-commit-hash.outputs.commit_hash }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: FuelLabs/fuel-indexer
          fetch-depth: 0

      - name: Set current date
        id: set-date
        run: |
          TODAY=$(date +'%Y%m%d')
          echo "::set-output name=today::$TODAY"
          echo "::set-output name=yesterday::$(date --date="$TODAY -1 day" +'%Y%m%d')"

      - name: Set commit hash
        id: set-commit-hash
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse --short=10 HEAD)"

      - name: Set tag 
        id: set-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          # trim v
          LATEST_TAG="${LATEST_TAG#v}"
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Set name
        id: set-name
        run: |
          NAME=fuel-indexer-${{ steps.set-tag.outputs.tag }}+nightly.${{ steps.set-date.outputs.today }}.${{ steps.set-commit-hash.outputs.commit_hash }}
          PLUGIN_NAME=forc-index-${{ steps.set-tag.outputs.tag }}+nightly.${{ steps.set-date.outputs.today }}.${{ steps.set-commit-hash.outputs.commit_hash }}
          echo "::set-output name=name::$NAME"
          echo "plugin_name=$PLUGIN_NAME" >> $GITHUB_OUTPUT

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          path: scripts

      - name: Create release notes (fuel-indexer)
        run: |
          ./scripts/.github/workflows/scripts/write-release-notes.sh fuel-indexer ${{ steps.set-date.outputs.yesterday }} ${{ steps.set-date.outputs.today }} 

      - name: Create Release (fuel-indexer)
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.set-name.outputs.name }}
          tag: ${{ steps.set-name.outputs.name }}
          allowUpdates: true
          removeArtifacts: true
          bodyFile: "body.md"
          draft: false 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release notes (forc-index)
        run: |
          ./scripts/.github/workflows/scripts/write-release-notes.sh forc-index ${{ steps.set-date.outputs.yesterday }} ${{ steps.set-date.outputs.today }} 

      - name: Create Release (forc-index)
        id: create-release-plugin
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.set-name.outputs.plugin_name }}
          tag: ${{ steps.set-name.outputs.plugin_name }}
          allowUpdates: true
          removeArtifacts: true
          bodyFile: "body.md"
          draft: false 
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Release fuel-indexer 
    runs-on: ${{ matrix.job.os }}
    needs: release
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            platform: linux
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            platform: linux
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            platform: darwin
            target: x86_64-apple-darwin
          - os: macos-latest
            platform: darwin
            target: aarch64-apple-darwin
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          repository: fuellabs/fuel-indexer

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
          key: "${{ matrix.job.target }}"

            
      - name: Install cargo-edit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-edit

      - name: Bump patch version and add nightly pre-release tag
        uses: actions-rs/cargo@v1
        with:
          command: set-version
          args: --metadata nightly.${{ needs.release.outputs.today }}.${{ needs.release.outputs.commit_hash }}

      - name: Use Cross
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cross
          cache-key: "${{ matrix.job.target }}"

      - name: Build fuel-indexer
        run: |
          cross build --profile=release --target ${{ matrix.job.target }} -p fuel-indexer

      - name: Build forc-index
        run: |
          cross build --profile=release --target ${{ matrix.job.target }} -p forc-index

      - name: Strip release binary x86_64-linux-gnu
        if: matrix.job.target == 'x86_64-unknown-linux-gnu'
        run: |
          strip "target/${{ matrix.job.target }}/release/fuel-indexer"
          strip "target/${{ matrix.job.target }}/release/forc-index"

      - name: Strip release binary aarch64-linux-gnu
        if: matrix.job.target == 'aarch64-unknown-linux-gnu'
        run: |
          docker run --rm -v \
          "$PWD/target:/target:Z" \
          ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main \
          aarch64-linux-gnu-strip \
          /target/aarch64-unknown-linux-gnu/release/fuel-indexer

          docker run --rm -v \
          "$PWD/target:/target:Z" \
          ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main \
          aarch64-linux-gnu-strip \
          /target/aarch64-unknown-linux-gnu/release/forc-index

      - name: Strip release binary mac
        if: matrix.job.os == 'macos-latest'
        run: |
          strip -x "target/${{ matrix.job.target }}/release/fuel-indexer"
          strip -x "target/${{ matrix.job.target }}/release/forc-index"

      - name: Prep Assets
        id: prep_assets
        run: |
          # prep fuel-indexer
          ARTIFACT="${{ needs.release.outputs.name }}-${{ matrix.job.target }}"
          ZIP_FILE_NAME="$ARTIFACT.tar.gz"
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV
          # create zip file
          mkdir -pv "$ARTIFACT"

          cp "target/${{ matrix.job.target }}/release/fuel-indexer "$ARTIFACT"

          tar -czvf $ZIP_FILE_NAME "$ARTIFACT"

          PLUGIN_ARTIFACT="${{ needs.release.outputs.plugin_name }}-${{ matrix.job.target }}"
          PLUGIN_ZIP_FILE_NAME="$PLUGIN_ARTIFACT.tar.gz"
          echo "PLUGIN_ZIP_FILE_NAME=$PLUGIN_ZIP_FILE_NAME" >> $GITHUB_ENV
          # create zip file
          mkdir -pv "$PLUGIN_ARTIFACT"

          cp "target/${{ matrix.job.target }}/release/forc-index "$PLUGIN_ARTIFACT"

          tar -czvf $PLUGIN_ZIP_FILE_NAME "$PLUGIN_ARTIFACT"


      - name: Upload release archive (fuel-indexer)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ env.ZIP_FILE_NAME }}
          asset_name: ${{ env.ZIP_FILE_NAME }}
          asset_content_type: application/gzip

      - name: Upload release archive (forc-index)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_ZIP_FILE_NAME }}
          asset_name: ${{ env.PLUGIN_ZIP_FILE_NAME }}
          asset_content_type: application/gzip

