name: Setup Cross Build Environment

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      cross_image:
        required: false
        type: string
      os:
        required: true
        type: string
      rust_version:
        required: false
        type: string
        default: "stable"

jobs:
  setup:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout fuel-core for Docker files
        if: inputs.cross_image
        uses: actions/checkout@v3
        with:
          repository: fuellabs/fuel-core
          path: fuel-core-ci

      - name: Set up Docker Buildx
        if: inputs.cross_image
        uses: docker/setup-buildx-action@v1

      - name: Setup custom cross env ${{ inputs.cross_image }}
        if: inputs.cross_image
        uses: docker/build-push-action@v2
        with:
          context: fuel-core-ci/ci
          file: fuel-core-ci/ci/Dockerfile.${{ inputs.target }}-clang
          tags: ${{ inputs.cross_image }}:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install packages (macOS)
        if: contains(inputs.os, 'macos')
        run: |
          brew install llvm

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust_version }}
          targets: ${{ inputs.target }},wasm32-unknown-unknown